/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:185b3898-4bac-4551-bf75-15e9ad1235cb",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_XHxrjDMQA",
    "aws_user_pools_web_client_id": "iqmnkl2c06fp73ciqedk53t1k",
    "oauth": {}
};


export default awsmobile;
